sources:
- platform: twitter
  data:
    enabled: true
    converters:
    - fxtwitter
    - vxtwitter
    - fixupx
    - fixvx
    selected: fxtwitter
- platform: bluesky
  data:
    enabled: true
    converters:
    - bsky
    - fxbsky
    - vxbsky
    - bskye
    - bskyx
    selected: bsky
